package com.example.githubtrailblazer.ui.myrepos;

import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.ViewModel;

// AUTOGENERATED view model

public class IssuesViewModel extends ViewModel {


}