package com.example.githubtrailblazer.ui.myrepos;

import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.ViewModel;

// AUTOGENERATED view model

public class MyReposViewModel extends ViewModel {

    private MutableLiveData<String> mText;

    public MyReposViewModel() {
        mText = new MutableLiveData<>();
        mText.setValue("This is my repos fragment");
    }

    public LiveData<String> getText() {
        return mText;
    }
}