package com.example.githubtrailblazer.ui.saved;

import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.ViewModel;

// AUTOGENERATED view model

public class SavedViewModel extends ViewModel {

    private MutableLiveData<String> mText;

    public SavedViewModel() {
        mText = new MutableLiveData<>();
        mText.setValue("This is saved fragment");
    }

    public LiveData<String> getText() {
        return mText;
    }
}